ANSWER NO 1

In [ ]:
import numpy as np
A=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
B=np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15],[16,17,18,19]])
print(A)
print(B)
C=np.matmul(A,B)
print(C)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 161  176  191  206]
 [ 366  406  446  486]
 [ 571  636  701  766]
 [ 776  866  956 1046]]


In [ ]:
C = np.zeros((4,4),dtype = int)
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            C[i][j] += A[i][k]* B[k][j]
print(C)            

[[ 161  176  191  206]
 [ 366  406  446  486]
 [ 571  636  701  766]
 [ 776  866  956 1046]]


ANSWER NO 2

In [ ]:


arr=np.random.randint(0,10,(5,5))
print(arr)
print('------------------------------')
At=np.transpose(arr)
print(At)
print('------------------------------')
mul=np.multiply(arr,At)
print(mul)

[[9 0 6 9 8]
 [3 6 4 9 1]
 [2 6 5 1 7]
 [7 9 8 8 6]
 [9 9 9 4 0]]
------------------------------
[[9 3 2 7 9]
 [0 6 6 9 9]
 [6 4 5 8 9]
 [9 9 1 8 4]
 [8 1 7 6 0]]
------------------------------
[[81  0 12 63 72]
 [ 0 36 24 81  9]
 [12 24 25  8 63]
 [63 81  8 64 24]
 [72  9 63 24  0]]


ANSWER NO 3

In [ ]:
A=np.random.randint(0,100,(4,4))
print(A)
print('----------------------------------------------')
determinant=np.linalg.det(A)
print(determinant)
print('----------------------------------------------')
inverse=np.linalg.inv(A)
print(inverse)

[[46 89 95 80]
 [36 33  9  9]
 [30 18 86 64]
 [59 98 80 53]]
----------------------------------------------
2632199.999999999
----------------------------------------------
[[-0.01275587  0.03945293  0.01392295 -0.00425804]
 [ 0.00935491 -0.01219588 -0.01744814  0.00901983]
 [-0.03890586 -0.0380541   0.01664349  0.04509004]
 [ 0.05562799  0.03607173 -0.00835879 -0.06113061]]


ANSWER NO 4

In [ ]:
A=np.random.randint(0,50,(6,6))
B=np.random.randint(0,50,(6,6))
print(A)
print('----------------------------------------------')
print(B)
print('----------------------------------------------')
C=np.dot(A,B)
print(C)
print('----------------------------------------------')
D=np.linalg.inv(C)
print(D)

[[14 13 22 38  0  4]
 [ 1 39 41 32  9 25]
 [27 43 42 39 47 20]
 [13 49 40 45 10 13]
 [ 0 20 27 23 36 10]
 [19 19 28 14 45  9]]
----------------------------------------------
[[15 21 19 23 34 13]
 [21  6 14 37 29 16]
 [ 2 12 15  7 31 32]
 [29 29 21 46  9 14]
 [36 32 10 16 11 33]
 [ 6 22 20 47 20 45]]
----------------------------------------------
[[1653 1826 1656 2893 1957 1806]
 [2318 2513 2442 4544 3323 3819]
 [4335 4404 3434 5992 4735 5380]
 [3047 2958 2838 5233 3878 3778]
 [2497 2483 1728 3033 2220 3144]
 [2820 2893 1971 3123 2866 3533]]
----------------------------------------------
[[-5.88469900e-04 -1.67710597e-03 -4.80385391e-03  4.18621171e-03
   2.89563724e-03  2.37559780e-03]
 [ 8.38903068e-05  3.80226137e-04  1.00670074e-02 -6.33926230e-03
  -3.92444791e-03 -5.51256505e-03]
 [ 6.45249282e-03  9.07605202e-04 -2.16868178e-02  8.32592788e-03
   6.38662776e-03  1.41581716e-02]
 [-1.69529090e-03 -1.85259245e-04  7.18214725e-03 -2.71530949e-03
  -1.27564348e-03 -5.83121692e-03]
 [